[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = 'runtime! dein/conf/deoplete.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/neosnippet'
on_i = 1
hook_add = 'runtime! dein/conf/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_i = 1
on_ft = 'snippet'
