tap homebrew/versions || true
tap sanemat/font || true
tap peco/peco || true
update || true
# tools
install zsh || true
install git || true
install hub || true
install tig || true
install tree || true
install jq || true
install peco || true
# for build
install imagemagick || true
install gsl || true
install bison || true
install ghostscript || true
# fonts
install ricty || true
# platforms
install haskell-platform || true
install node || true
